package com.ceva.batch.split.common;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Constant {
  public static final String PROFILE = "junit";
  public static final String USERNAME = "aaf.admin";
  public static final String PERMISSION = "aaf_permission:*:*";
  public static final String CORRELATION_ID = "correlation-id";
  public static final String YES = "YES";
  public static final String BOOKING = "BOOKING";
  public static final String MILESTONE = "MILESTONE";
  public static final String CFASTBI = "cfastbi";
  public static final String NO_RESULTS_FOUND = "No results found";
  public static final String UTC_TIME_ZONE_CODE = "UTC";
  public static final String DEFAULT_DATE_FORMAT_FOR_TIMESTAMP_ZONE = "yyyy-MM-dd'T'HH:mm:ss zzz";
  public static final String ULTIMATE_CONSIGNEE = "UltimateConsignee";
  public static final String IMPORTER_OF_RECORD = "ImporterOfRecord";
  public static final String HOU = "HOU";
  public static final String TST = "TST";
  public static final String PRD = "PRD";
  public static final String TS1 = "TS1";
  public static final String MID = "MID";
  public static final String EIN = "EIN";
  public static final String FTZ = "FTZ";
  public static final String WAYBILLISSUERSCAC = "WayBillIssuerSCAC";
  public static final String ENTRYSUBMITTED = "EntrySubmitted";
  public static final String LIQUIDATIONDATE = "LiquidationDate";
  public static final String LIQUIDATIONTYPE = "LiquidationType";
  public static final String MASTERWAYBILLISSUERSCAC = "MasterWayBillIssuerSCAC";
  public static final String MWB = "MWB";
  public static final String MASTERWAYBILLNUMBER = "MasterWayBillNumber";
  public static final String OFS = "OFS";
  public static final String PERIODICSTATEMENTMM = "PeriodicStatementMM";
  public static final String PORTOFCLEARANCE = "PortOfClearance";
  public static final String HWB = "HWB";
  public static final String OTHERRECONINDICATOR = "OtherReconIndicator";
  public static final String SIN = "SIN";
  public static final String VAT = "VAT";
  public static final String DTY = "DTY";
  public static final String ONS = "ONS";
  public static final String OFT = "OFT";
  public static final String CUSTOMSDECLARATION = "CustomsDeclaration";
  public static final String SUBLOCATIONCODE = "SubLocationCode";
  public static final String STATEMENTNUMBER = "StatementNumber";
  public static final String K84ACCOUNTINGDATE = "K84AccountingDate";
  public static final String SCHDENTRY = "SchDEntry";
  public static final String SCHDARRIVAL = "SchDArrival";
  public static final String ARRIVAL = "Arrival";
  public static final String US = "US";
  public static final String CA = "CA";
  public static final String ZA = "ZA";
  public static final String SELLER = "seller";
  public static final String MANUFACTURER = "manufacturer";
  public static final String GET = "GET";
  public static final String RATE = "Rate";
  public static final String ONE_CHAR_SPACE = " ";
  public static final String COTTONFEEEXEMPT = "CottonFeeExempt";
  public static final String DONOTEDIT = "DO NOT EDIT";
  public static final String ORIGINALAMOUNT = "OriginalAmount";
  public static final String EXEMPTCODE = "ExemptCode";
  public static final String GST = "GST";
  public static final String TAXTYPE = "TaxType";
  public static final String FEE = "FEE";
  public static final String EXS = "EXS";
  public static final String CDT = "CDT";
  public static final String FNN = "499";
  public static final String SUPPLIER = "Supplier";
  public static final String REFRESHAPI = "REFRESHAPI";
  public static final String WRITE_TO_TOPIC_FAILED = "Problem occured While posting";
  public static final String NO_TOPIC_FOUND = "Topic information is not available";
  public static final String AMOUNT = "Amount";
  public static final String ADD = "ADD";
  public static final String CVD = "CVD";
  public static final String TRANSPORTLEG = "TRANSPORTLEG";
  public static final String FORWARDING_SHIPMENT = "ForwardingShipment";
  public static final String FORWARDINGSHIPMENT = "FORWARDINGSHIPMENT";
  public static final String FORWARDING_CONSOL = "ForwardingConsol";
  public static final String FORWARDINGBOOKING = "ForwardingBooking";
  public static final String SHIPMENT = "SHIPMENT";
  public static final String DOMESTIC = "DOMESTIC";
  public static final String EXPORT = "EXPORT";
  public static final String IMPORT = "IMPORT";
  public static final String CROSS = "CROSS";
  public static final String CONSOL = "Consol";
  public static final String DIRECT = "Direct";
  public static final String INTERNATIONAL = "International";
  public static final String CFAST_BI_LOCATION = "cfast_bi_location";
  public static final String DATA_TABLE_CFAST_BI_LOCATION = "cfast_bi_location";
  public static final String DATA_TABLE_CFAST_BI_COMPANY_CODE = "cfast_bi_company_code";
  public static final String CFAST_BI_COMPANY_CODE = "cfast_bi_product_ofs";
  public static final String CFAST_BI_PACKING_TYPE = "cfast_bi_packing_type";
  public static final String CFAST_BI_COMMODITY = "cfast_bi_commodity";
  public static final String SID = "SID";
  public static final String CfastBi_TABLE = "CfastBi";
  public static final String EVENT_TABLE = "event";
  public static final String DRT = "DRT";
  public static final String INDUSTRIAL_PROJECT_ENERGY = "INDUSTRIAL PROJECT - ENERGY";
  public static final String CWOORGPK = "CWOORGPK";
  public static final String SHIPPER = "Shipper";
  public static final String ISSUE = "Issue";
  public static final String NOTIFY = "Notify";
  public static final String DELIVERY = "Delivery";
  public static final String PICKUP = "Pickup";
  public static final String PAYER = "Payer";
  public static final String CUSTOMER = "Customer";
  public static final String CONSIGNEE = "Consignee";
  public static final String SEA = "SEA";
  public static final String AIR = "AIR";
  public static final String OCEAN = "OCEAN";
  public static final String CEVA = "CEVA";
  public static final String ImportBroker = "ImportBroker";
  public static final String ExportBroker = "ExportBroker";
  public static final String CO2 = "CO2";
  public static final String SH = "SH";
  public static final String FTS = "FTS";
  public static final String CO = "CO";
  public static final String ITN = "ITN";
  public static final String M3 = "M3";
  public static final String CF = "CF";
  public static final String KG = "KG";
  public static final String LB = "LB";
  public static final String IN = "IN";
  public static final String CM = "CM";

  protected static final List<String> importBrokerageValuesTrue =
      new ArrayList<>(Arrays.asList("DC", "PC"));
  protected static final List<String> importBrokerageValuesFalse =
      new ArrayList<>(Arrays.asList("DN", "HD", "HN", "NN", "PN"));
  public static final String COMMA = ",";
  public static final String BILL = "BillTo";
  public static final String FORWARDER = "Forwarder";
  public static final String TERMINAL = "Terminal";
  public static final String HAULIER = "Haulier";
  public static final String CARRIER = "Carrier";
  public static final String AGENT = "Agent";
  public static final String X3 = "X3";
  public static final String NOTIFY2 = "Notify2";
  public static final String NOTIFY3 = "Notify3";
  public static final String NOTIFY4 = "Notify4";
  public static final String SHIPPERLA = "ShipperLA";
  public static final String CONSIGNEELA = "ConsigneeLA";
  public static final String CUSTOMERLA = "CustomerLA";
  public static final String ISSUELA = "IssueLA";
  public static final String DELIVERYLA = "DeliveryLA";
  public static final String HAULIERLA = "HaulierLA";
  public static final String TERMINALLA = "TerminalLA";
  public static final String PICKUPLA = "PickupLA";
  public static final String X3LA = "X3LA";
  public static final String CWO = "CWO";
  public static final String EVENT = "EVENT";
  public static final String ARV = "ARV";
  public static final String CID = "CID";
  public static final String SEMICOLON = ";";
  public static final boolean False = false;
  public static final String TRANSACTION = "TRANSACTION";
  public static final String AP = "AP";
  public static final String AR = "AR";
  public static final String WIP = "WIP";
  public static final String ACR = "ACR";
  public static final String CREDITOR = "CREDITOR";
  public static final String DEBTOR = "DEBTOR";
  public static final String FINANCE = "FINANCE";
  public static final String DELIMETER = "_";
  public static final String ACTUAL = "ACTUAL";
  public static final String ESTIMATED = "ESTIMATED";
  public static final String DepartureDateTime = "DepartureDateTime";
  public static final String ArrivalDateTime = "ArrivalDateTime";
  public static final String MainDateTime = "MainDateTime";
  public static final String PickUpDateTime = "PickUpDateTime";
  public static final String PickUpEndDateTime = "PickUpEndDateTime";
  public static final String DueDateTime = "DueDateTime";
  public static final String HYPHEN = "-";
  public static final String BATCH = "batch-split";

  public static List<String> getImportbrokeragevaluestrue() {
    return importBrokerageValuesTrue;
  }

  public static List<String> getImportbrokeragevaluesfalse() {
    return importBrokerageValuesFalse;
  }
}
