package com.ceva.batch.split.enums;

public enum DestinationEnum {

  MILESTONE, BOOKING, TRANSPORTLEG, FINANCIAL, EXCEPTION, 
  MILESTONESUMMARY, CARBONEMISSION, TRIPPLAN, HOUSE, PROFILE, 
  EVENTS, MASTER, MYCEVA, UNKNOWN, DATACONVERSION, SHIPMENT, FINANCE, GeneralLedegerIds;

}
